name: quran_app
description: A new Flutter project for Quran App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  intl: ^0.19.0
  adhan: ^2.0.0
  quran: 1.2.0
  just_audio: ^0.9.36
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  geolocator: ^10.1.0
  flutter_compass: ^0.8.0
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  bloc_test: ^9.1.5
  mocktail: ^1.0.2

flutter:
  uses-material-design: true
