name: quran_app
description: A new Flutter project for Quran App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  alfurqan: ^0.0.4
  flutter_timezone: ^5.0.1
  timezone: ^0.9.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  intl: ^0.19.0
  adhan: ^2.0.0
  quran: 1.2.0
  just_audio: ^0.9.36
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_compass: ^0.8.0
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  share_plus: ^7.2.2
  flutter_tts: ^3.8.5
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  bloc_test: ^9.1.5
  mocktail: ^1.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/illustrations/
    - assets/translations/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
